### DISCUSSION TITLE
Docker Image?

### DISCUSSION THREAD

**Discussion by r0073d-l053r** [DustinBrett/daedalOS#196] [Q&A] [answered]
Do you by chance have a Docker image for this project yet? I started drafting a compose.yml for this and I was just curious what the image may be?

Here is what I've composed so far, everything #commented out is more geared toward my reverse proxy environment.
```yml

`version: '3.3'
services:
    daedalos:
        # networks:
        #     - nginx
        expose:
            - 3000
        container_name: daedalos
        image: ****daedalos****
        environment:
            - VIRTUAL_HOST=daedalos.yourdomain.com
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=daedalos.yourdomain.com
        volumes:
            - /srv/daedalos/config:/config
        restart: unless-stopped
# networks:

#     nginx:
#         external: true
`
```
